import type { CurrentAffairsItem } from './current-affairs-schema';

/** Source-first Hindi fallback pack. Live Firestore items take precedence. */
export const HINDI_CURRENT_AFFAIRS: CurrentAffairsItem[] = [
  { id:'ca-2026-08-25-eshram', title:'ई-श्रम पोर्टल के 5 वर्ष: असंगठित श्रमिकों के लिए डिजिटल सामाजिक सुरक्षा', source:'PIB', link:'https://www.pib.gov.in/PressReleasePage.aspx?PRID=2303053&lang=2&reg=48', publishedAt:Date.parse('2026-08-25T14:38:00+05:30'), summary:'ई-श्रम पोर्टल 26 अगस्त 2021 को शुरू हुआ था। 20 अगस्त 2026 तक 31.89 करोड़ पंजीकरण दर्ज किए गए। यह असंगठित श्रमिकों के लिए सामाजिक सुरक्षा, रोजगार, कौशल और पेंशन सेवाओं तक एकीकृत डिजिटल पहुँच देता है।', examRelevance:'GS-II: सामाजिक सुरक्षा, कल्याणकारी योजनाओं की डिलीवरी और डिजिटल शासन; GS-III: अनौपचारिक क्षेत्र और श्रम बाज़ार।', topic:'सामाजिक सुरक्षा एवं डिजिटल शासन', category:'social-issues', gsPaper:'GS2, GS3', createdAt:Date.parse('2026-08-25T14:38:00+05:30') },
  { id:'ca-2026-08-24-upi', title:'UPI के 10 वर्ष: भारत की डिजिटल सार्वजनिक अवसंरचना का वैश्विक विस्तार', source:'PIB', link:'https://www.pib.gov.in/PressReleasePage.aspx?PRID=2302657&lang=1&reg=48', publishedAt:Date.parse('2026-08-24T13:57:00+05:30'), summary:'UPI ने एक दशक पूरा किया। FY 2025-26 में 24,162 करोड़ से अधिक वार्षिक लेन-देन और लगभग ₹314 लाख करोड़ का मूल्य दर्ज हुआ। 2026 में 703 बैंक UPI से लाइव थे और यह 11 देशों में परिचालित था।', examRelevance:'DPI, वित्तीय समावेशन, फिनटेक, साइबर सुरक्षा और डिजिटल शासन के लिए Prelims तथा GS-III।', topic:'डिजिटल सार्वजनिक अवसंरचना एवं फिनटेक', category:'economy', gsPaper:'GS3', createdAt:Date.parse('2026-08-24T13:57:00+05:30') },
  { id:'ca-2026-08-23-regenerative-agriculture', title:'पुनर्योजी कृषि: मिट्टी, जल और जलवायु-लचीलापन पर जोर', source:'PIB', link:'https://www.pib.gov.in/PressNoteDetails.aspx?ModuleId=3&NoteId=159690&id=159690&lang=2&reg=48', publishedAt:Date.parse('2026-08-23T10:28:00+05:30'), summary:'प्राकृतिक खेती, कृषि-वनीकरण, सूक्ष्म सिंचाई, एकीकृत कृषि प्रणालियाँ और वैज्ञानिक मृदा प्रबंधन को कृषि-लचीलापन के लिए बढ़ावा दिया जा रहा है। मार्च 2026 तक प्राकृतिक खेती क्लस्टर 8.80 लाख हेक्टेयर और 18.19 लाख किसानों तक पहुँचे थे।', examRelevance:'GS-III: जलवायु-स्मार्ट कृषि, मृदा स्वास्थ्य, जल दक्षता और टिकाऊ कृषि।', topic:'जलवायु-स्मार्ट एवं पुनर्योजी कृषि', category:'agriculture', gsPaper:'GS3', createdAt:Date.parse('2026-08-23T10:28:00+05:30') },
  { id:'ca-2026-08-22-nadcp', title:'राष्ट्रीय पशु रोग नियंत्रण कार्यक्रम: पशुधन स्वास्थ्य और किसान आय', source:'PIB', link:'https://www.pib.gov.in/PressReleasePage.aspx?PRID=2302242&lang=1&reg=48', publishedAt:Date.parse('2026-08-22T10:24:00+05:30'), summary:'2019 में शुरू NADCP का लक्ष्य FMD और Brucellosis को टीकाकरण तथा निगरानी से नियंत्रित करना है। PIB के अनुसार 147.16 करोड़ FMD वैक्सीन डोज दी गईं और 8.04 करोड़ किसान लाभान्वित हुए।', examRelevance:'GS-III: पशुधन अर्थव्यवस्था, One Health, टीकाकरण और पशु रोग निगरानी।', topic:'पशुधन स्वास्थ्य एवं One Health', category:'agriculture', gsPaper:'GS3', createdAt:Date.parse('2026-08-22T10:24:00+05:30') },
  { id:'ca-2026-08-21-pm-aasha', title:'PM-AASHA: MSP आधारित मूल्य समर्थन को मजबूत करने पर जोर', source:'PIB', link:'https://www.pib.gov.in/PressReleasePage.aspx?PRID=2301814&lang=1&reg=48', publishedAt:Date.parse('2026-08-21T10:43:00+05:30'), summary:'PM-AASHA किसानों को लाभकारी मूल्य दिलाने और distress sale घटाने का मूल्य-समर्थन ढाँचा है। 2026-27 के लिए ₹7,200 करोड़ का बजट आवंटन बताया गया है। PSS, PSF, PDPS और MIS इसके प्रमुख घटक हैं।', examRelevance:'GS-III: MSP, कृषि मूल्य नीति, खाद्य मुद्रास्फीति, बाजार सुधार और किसान आय।', topic:'MSP एवं कृषि मूल्य नीति', category:'agriculture', gsPaper:'GS3', createdAt:Date.parse('2026-08-21T10:43:00+05:30') },
  { id:'ca-2026-08-20-pmjvm', title:'प्रधानमंत्री जनजातीय विकास मिशन: Minor Forest Produce से जनजातीय उद्यमिता', source:'PIB', link:'https://www.pib.gov.in/PressReleasePage.aspx?PRID=2301419&lang=1&reg=3', publishedAt:Date.parse('2026-08-20T11:03:00+05:30'), summary:'PMJVM Minor Forest Produce पर निर्भर जनजातीय समुदायों को मूल्य-वर्धन, बाजार और उद्यमिता से जोड़ता है। PIB के अनुसार 4,172 Van Dhan Vikas Kendras स्वीकृत हैं और 12.48 लाख जनजातीय सदस्य जुड़े हैं।', examRelevance:'GS-II/III: आदिवासी विकास, MFP, आजीविका, मूल्य श्रृंखला और समावेशी विकास।', topic:'जनजातीय आजीविका एवं Minor Forest Produce', category:'social-issues', gsPaper:'GS2, GS3', createdAt:Date.parse('2026-08-20T11:03:00+05:30') },
  { id:'ca-2026-08-19-makhana', title:'मखाना क्षेत्र: पारंपरिक फसल से वैश्विक agri-food value chain तक', source:'PIB', link:'https://www.pib.gov.in/PressReleasePage.aspx?PRID=2301052&lang=2&reg=48', publishedAt:Date.parse('2026-08-19T10:24:00+05:30'), summary:'भारत विश्व का सबसे बड़ा मखाना उत्पादक है और बिहार देश के उत्पादन का लगभग तीन-चौथाई देता है। 2025-26 में 7,264.89 MT मखाना उत्पाद निर्यात हुए। मखाना विकास के लिए ₹476.03 करोड़ की Central Sector Scheme और National Makhana Board पर जोर है।', examRelevance:'GS-III: कृषि विविधीकरण, GI, FPO, value addition और कृषि निर्यात।', topic:'कृषि मूल्य श्रृंखला एवं GI', category:'agriculture', gsPaper:'GS3', createdAt:Date.parse('2026-08-19T10:24:00+05:30') },
  { id:'ca-2026-08-18-mmrd', title:'MMDR Amendment Act 2026: खनिज शासन और रणनीतिक संसाधन', source:'PIB', link:'https://www.pib.gov.in/AllRelease.aspx?MenuId=23&PMO=1&lang=1&reg=1', publishedAt:Date.parse('2026-08-18T10:00:00+05:30'), summary:'PIB के अगस्त 2026 backgrounders में MMDR Amendment Act 2026 प्रमुख विषयों में है। इसे खनिज संसाधन शासन, critical minerals, संघ-राज्य संबंध और ऊर्जा संक्रमण के संदर्भ में पढ़ना उपयोगी है।', examRelevance:'GS-II: संघ-राज्य आयाम; GS-III: खनिज संसाधन, critical minerals और ऊर्जा संक्रमण।', topic:'खनिज शासन एवं Critical Minerals', category:'governance', gsPaper:'GS2, GS3', createdAt:Date.parse('2026-08-18T10:00:00+05:30') }
];
